FROM node:18-slim

# Set working directory
WORKDIR /app

# Copy package files and install dependencies
COPY package.json package-lock.json ./
RUN npm install

# Copy the source files
COPY ./src ./src
COPY ./public ./public

# Expose React's development server port
EXPOSE 3000

# Start the React development server
CMD ["npm", "start"]
